React capstone project - Metrics webapp
aliabbani/Metrics-webapp pull request #4
Opened 2021-10-14 13:29 UTC by aliabbani

## React capstone project - Metrics webapp

In this milestone we:

- Used correct Gitflow.
- The app is a single-page application (SPA) built with React and Redux.
- We find [Covid](https://covid19tracking.narrativa.com/index_en.html) API to base the development of the app around it.
- When the home page loads, the webapp shows the list of countries with numeric values for the historical total cases.
- When the user clicks (or taps) on a country item, the application navigates to the details page.
- When the details page loads, the webapp shows detailed data for a specific country.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- Created tests for the application.
- Styled your components to match the design provided.

[Project video Link](https://drive.google.com/file/d/1AS8uwawW_O2ObDgGVv_ed8ZgBfiFme9p/view) 

We Also:
- Added a new repo
- Created react-redux app
- Added linters
- Added reducer, store, and components.
- Added CSS file
- Added test

2021-10-14 15:15 UTC, henatan99 requested changes
Hi @aliabbani , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] I cannot find a video link either in your PR summary or in the readme file. Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:
- a description of the project. 
- a demo of the project features.
- you should also highlight some interesting piece of code or something you built that you are very proud of.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 15:15 UTC, henatan99 commented on src/stylesheet/index.css
> +  align-items: end;
- [x] The `align-item` property `end` has mixed support so preventing the app from running. I think you can use the `flex-end` property. Kindly make the required change here. :pray: 

![Screenshot from 2021-10-14 17-20-18](https://user-images.githubusercontent.com/64894927/137337020-a69af02a-6f0d-44fa-92b0-82a561bbf295.png)

2021-10-14 15:15 UTC, henatan99 commented on README.md
> +Original design idea by Nelson Sakwa on [Behance](https://www.behance.net/gallery/31579789/Ballhead-App-%28Free-PSDs%29).
- [x] I think you should take this line under the acknowledgment section. :pray:

2021-10-14 15:15 UTC, henatan99 commented on src/components/Home.js
> +            </div>
- [x] I think this card component can be a separate component that can be imported and rendered here. React is a component-based framework and smaller components are more convenient for reusability, fixing bugs and errors and app scalability. :pray:

2021-10-14 15:15 UTC, henatan99 commented on src/stylesheet/index.css
> +}
- [ ] The card components should be distinguished horizontally as well using either horizontal borders or some diagonal color pattern like in the original design which would improve the UX. :pray: 

![image](https://user-images.githubusercontent.com/64894927/137345190-27abcfb6-d78d-457e-bd57-99e98eab7e30.png)
![image](https://user-images.githubusercontent.com/64894927/137345272-efafe6c3-32ea-40eb-ae0f-16c7c8a67875.png)

2021-10-15 08:39 UTC, aliabbani commented on README.md
> +Original design idea by Nelson Sakwa on [Behance](https://www.behance.net/gallery/31579789/Ballhead-App-%28Free-PSDs%29).
Hi @henatan99 thank you for your comment, I moved it as you can see in the image below

![comment2](https://user-images.githubusercontent.com/60292761/137456265-0f281bc8-fb9f-4184-8b53-3b3f0bb5f195.PNG)

2021-10-15 08:39 UTC, aliabbani commented on src/stylesheet/index.css
> +  align-items: end;
Hi @henatan99 thank you for your comment, I solved it as you can see in the image below

![first-comment](https://user-images.githubusercontent.com/60292761/137455915-0e666855-28d6-4ccc-bbeb-e6bd622f6265.PNG)

2021-10-15 08:39 UTC, aliabbani commented on src/stylesheet/index.css
> +}
Hi @henatan99 thank you for your comment, I fixed the UI as you can see in the image below

![comment4](https://user-images.githubusercontent.com/60292761/137456542-d703c72d-6056-45b1-9b1e-d2739e526f5f.PNG)
![Capture](https://user-images.githubusercontent.com/60292761/137456597-f995ad83-b227-4cac-b715-d1c6cbf4c02a.PNG)

2021-10-15 08:58 UTC, aliabbani commented on src/components/Home.js
> +            </div>
Hi @henatan99 thank you for your comment, I created HomeHeader and HomeCountries components as you can see in the image below

![Capture333333](https://user-images.githubusercontent.com/60292761/137461391-e8c4de8b-9a04-4be5-a523-892d1119fdbb.PNG)

2021-10-15 09:58 UTC, henatan99 commented on src/stylesheet/index.css
> +  align-items: end;
This issue is well addressed. Nice work! :clap: :+1:

2021-10-15 09:59 UTC, henatan99 commented on README.md
> +Original design idea by Nelson Sakwa on [Behance](https://www.behance.net/gallery/31579789/Ballhead-App-%28Free-PSDs%29).
This issue is well addressed. Good job! :pray:

2021-10-15 10:01 UTC, henatan99 commented on src/stylesheet/index.css
> +}
This issue is well addressed. Great job! :clap: :+1:

2021-10-15 10:16 UTC, henatan99 approved these changes
Hi @aliabbani , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 10:16 UTC, henatan99 commented on src/components/Home.js
> +      <HomeCountries datas={datas} />
- [x] OPTIONAL: I am very glad you make the requested changes and make use of smaller components here. I also suggest that the `h5` element could have been better inserted inside the `HomeCountries` component. It is not required for this project submission but you can take your time later to make this change. :+1:

2021-10-15 10:19 UTC, merged